name: rf_classification
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0
  - pytorch-cuda=11.7
  - lightning>=2.0
  - torchmetrics
  - tensorboard
  - scikit-learn
  - numpy
  - scipy
  - h5py
  - matplotlib
  - seaborn
  - jupyterlab
  - ipywidgets  
